### ISSUE TITLE
mjs dist is transpiled?

### ISSUE THREAD

**Issue by fuzetsu** [ArthurClemens/mithril-hookup#2]
Just checking if it's intentional that the mjs build is transpiled. I would think it would be better to just copy the main src file instead? 

If the environment supports esm modules it's fairly likely it supports spread operators / destructuring / arrow functions, no?

The dist code is quite a bit larger than the original source file as a result.

**Comment by ArthurClemens** [comment]
The goal of es modules is to [use them in modern browsers without further transpiling](https://developers.google.com/web/fundamentals/primers/modules#browser).

If your goal is to import the code in an application, your bundler will further transpile the code.

My experience is that the method of processing source > rollup > webpack app works well - at least before webpack 4, it may be different now.

**Comment by fuzetsu** [comment]
Maybe I'm misunderstanding, but aren't we agreeing then that the mjs build in the dist folder should not be pre-transpiled? 

[Currently it's full of babel's generated utils](https://github.com/ArthurClemens/mithril-hookup/blob/master/dist/mithril-hookup.mjs#L1-L91)

**Comment by ArthurClemens** [comment]
Transpilation is still needed for browsers that do not support es2015+ features such as object spread.

But I will try to finetune this a bit more.

**Comment by fuzetsu** [comment]
I understand that for the CJS build, but do any browsers that support `export/import` not support arrow functions / object spread?

browser support:
![image](https://user-images.githubusercontent.com/848652/54286383-23c5c100-457a-11e9-92fd-9a19e8c5921f.png)

**Comment by ArthurClemens** [comment]
No: import/export is ECMAScript 2015, object spread is ECMAScript 2018.

**Comment by fuzetsu** [comment]
Ah, thanks for clarifying :)

I guess browsers implement this stuff out of order, since object spread seems to be supported in earlier browser version than ES modules (with a few exceptions).

![image](https://user-images.githubusercontent.com/848652/54290843-0eed2b80-4582-11e9-963e-4869c0c401b5.png)

This reasoning makes sense though, so I'll close 👍
